package org.ipro.crud;

import jakarta.persistence.Version;
import jakarta.persistence.OneToMany;
import org.hibernate.proxy.HibernateProxy;
import org.ipro.metadata.TableSectionMetadataInfo;
import org.ipro.numbering.annotation.Numbered;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.IdentityHashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Restores platform-managed input state when an aggregate transaction rolls back.
 * JPA rollback restores the database, but leaves generated IDs and other technical
 * values in the caller's objects. The same form must remain editable and retryable.
 *
 * <p>Only the root and supplied rows are inspected, never association graphs or absent
 * sections. Business fields remain untouched. Field annotations follow the platform's
 * metadata contract; identity uses IdentifiableEntity, including custom base classes.</p>
 */
final class AggregateSaveRollbackState implements TransactionSynchronization {

    private final Map<IdentifiableEntity, EntityState> entities = new IdentityHashMap<>();

    static AggregateSaveRollbackState current() {
        if (!TransactionSynchronizationManager.isActualTransactionActive()
                || !TransactionSynchronizationManager.isSynchronizationActive()) {
            throw new IllegalStateException("Aggregate save requires an active transaction");
        }
        // Repeated saves in one outer transaction must restore the earliest state,
        // not IDs generated by an earlier, still uncommitted save of the same object.
        for (TransactionSynchronization synchronization
                : TransactionSynchronizationManager.getSynchronizations()) {
            if (synchronization instanceof AggregateSaveRollbackState state) {
                return state;
            }
        }
        AggregateSaveRollbackState state = new AggregateSaveRollbackState();
        TransactionSynchronizationManager.registerSynchronization(state);
        return state;
    }

    void capture(IdentifiableEntity entity, TableSectionMetadataInfo section) {
        IdentifiableEntity target = entity instanceof HibernateProxy proxy
            ? (IdentifiableEntity) proxy.getHibernateLazyInitializer().getImplementation()
            : entity;
        EntityState state = entities.computeIfAbsent(target, EntityState::new);
        if (section != null) {
            state.capture(section.getParentField());
            if (section.hasLineNumberField()) {
                state.capture(section.getLineNumberField());
            }
        }
    }

    @Override
    public void afterCompletion(int status) {
        try {
            // Unknown completion is not proof of rollback: never make a possibly
            // committed entity appear new and invite a duplicate insert.
            if (status == STATUS_ROLLED_BACK) {
                entities.values().forEach(EntityState::restore);
            }
        } finally {
            entities.clear();
        }
    }

    private static final class EntityState {
        private final IdentifiableEntity entity;
        private final Long id;
        private final Map<Field, Object> fields = new LinkedHashMap<>();

        private EntityState(IdentifiableEntity entity) {
            this.entity = entity;
            this.id = entity.getId();
            for (Class<?> type = entity.getClass(); type != Object.class; type = type.getSuperclass()) {
                for (Field field : type.getDeclaredFields()) {
                    if (!Modifier.isStatic(field.getModifiers()) && isPlatformManaged(field)) {
                        capture(field);
                    }
                }
            }
        }

        private void capture(Field field) {
            if (fields.containsKey(field)) {
                return;
            }
            try {
                field.setAccessible(true);
                fields.put(field, field.get(entity));
            } catch (IllegalAccessException exception) {
                throw new IllegalStateException("Cannot snapshot aggregate field " + field, exception);
            }
        }

        private void restore() {
            entity.setId(id);
            for (Map.Entry<Field, Object> entry : fields.entrySet()) {
                try {
                    entry.getKey().set(entity, entry.getValue());
                } catch (IllegalAccessException exception) {
                    throw new IllegalStateException(
                        "Cannot restore aggregate field " + entry.getKey(), exception);
                }
            }
        }

        private static boolean isPlatformManaged(Field field) {
            return field.isAnnotationPresent(Version.class)
                // Hibernate may replace a new aggregate's collection with a persistent
                // wrapper before a later section vetoes the transaction. Restore the
                // caller-owned collection reference so the still-open form can retry.
                || field.isAnnotationPresent(OneToMany.class)
                || field.isAnnotationPresent(Numbered.class)
                || field.isAnnotationPresent(CreatedBy.class)
                || field.isAnnotationPresent(CreatedDate.class)
                || field.isAnnotationPresent(LastModifiedBy.class)
                || field.isAnnotationPresent(LastModifiedDate.class);
        }
    }
}
